# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-ast
      - id: check-added-large-files
  - repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
      - id: codespell
        args: [-H, -f, --builtin, clear, rare, informal, usage, code]
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: [
          "--python-version=auto", # Tells isort to set the known standard library based on the specified Python version.
          "--balanced", # Balances wrapping to produce the most consistent line length possible
          "--multi-line=10", # Hanging Indent with parenthesis.
          "--combine-as", # Combines as imports on the same line.
          "--combine-star", # Ensures that if a star import is present, nothing else is imported from that namespace.
          "--ensure-newline-before-comments", # Inserts a blank line before a comment following an import.
          "--project=nala" # Force isort to recognize a module as being part of the current python project.
        ]
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.0
    hooks:
      - id: pyupgrade
        args: ["--py38-plus"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.930
    hooks:
      - id: mypy
        args: [
          "--ignore-missing-imports",
          "--strict",
          "--pretty",
          "--show-error-context",
          "--show-column-numbers",
          "--show-error-codes",
          "--no-warn-unused-ignores"
        ]
