[package]
name = "nala-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-apt = { git = "https://gitlab.com/volian/rust-apt" }
#rust-apt = { path = "../rust-apt" }
# rust-apt = "*"
clap = { version = "4", features = ["derive"] }
lazy_static = "1.4"
toml = "0.5"
anyhow = "1.0"
regex = "1.6"
globset = "0.4.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = { version = "0.11", features = ["json", "blocking"] }
tokio = { version = "1", features = ["full"] }
once_cell = "1.18.0"
bytes = "1.5.0"
indicatif = "0.17.7"

[build-dependencies]
clap = { version = "4", features = ["derive"] }
clap_complete = "*"

[profile.dev]
opt-level = 1

[profile.lto]
# A profile with various additional optimizations
inherits = "release"

# It isn't clear that lto makes anything faster yet
# But it does reduce the binary size. true = "fat", can also use "thin"
lto = true

# Can't really tell if this changes anything
# codegen-units = 1

panic = "abort"
